import type { NextPage } from "next";
import { useTheme } from "next-themes";
import Head from "next/head";
import Board from "../containers/Board";
import DarkModeButton from "../components/DarkModeButton";

const Home: NextPage = () => {
  const { theme, setTheme } = useTheme();

  return (
    <div className="min-h-screen bg-background-default dark:bg-background-dark box-border p-10 pt-20 md:p-20">
      <Head>
        <title>3D Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DarkModeButton
        darkMode={theme === "light"}
        onClick={() => setTheme(theme === "light" ? "dark" : "light")}
      />
      <main className=" flex flex-col justify-center items-center ">
        <Board />
      </main>
    </div>
  );
};

export default Home;
