import type { NextPage } from "next";
import { useTheme } from "next-themes";
import Head from "next/head";
import Board from "../containers/Board";
import DarkModeButton from "../components/DarkModeButton";

const Home: NextPage = () => {
  const { theme, setTheme } = useTheme();
  console.log(theme);
  return (
    <div>
      <Head>
        <title>3D Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen flex flex-col justify-center items-center bg-background-default dark:bg-background-dark">
        <DarkModeButton
          darkMode={theme === "light"}
          onClick={() => setTheme(theme === "light" ? "dark" : "light")}
        />

        <Board />
      </main>
    </div>
  );
};

export default Home;
